// This file is auto-generated by generateServiceMap.ts
import { DatastoreService } from "../Services/DatastoreService";
import { GameService } from "../Services/GameService";
import { TestService } from "../Services/TestService";

export type Services = {
  DatastoreService: DatastoreService;
  GameService: GameService;
  TestService: TestService;
};
